### ISSUE TITLE
pth

### ISSUE THREAD

**Issue by ads2d** [lixinustc/KVQ-Challenge-CVPR-NTIRE2024#5]
Hello, this error occurred when I wanted to train the model. How can I download this pth file?

/home/jinw/anaconda3/envs/KVQ/lib/python3.8/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
pretrained_weights/swin_tiny_patch244_window877_kinetics400_1k.pth False
loading swin lah
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from trainer import Trainer
  File "/home/jinw/VQA/KVQ/trainer.py", line 29, in <module>
    from models.model import VQA_Network 
  File "/home/jinw/VQA/KVQ/models/__init__.py", line 1, in <module>
    from .model import *
  File "/home/jinw/VQA/KVQ/models/model.py", line 8, in <module>
    from models.backbones.swin_backbone import swin_3d_small, swin_3d_tiny
  File "/home/jinw/VQA/KVQ/models/backbones/__init__.py", line 3, in <module>
    from .swin_backbone import SwinTransformer2D as IQABackbone
  File "/home/jinw/VQA/KVQ/models/backbones/swin_backbone.py", line 1108, in <module>
    SwinTransformer3D(window_size=(8, 7, 7),)
  File "/home/jinw/VQA/KVQ/models/backbones/swin_backbone.py", line 842, in __init__
    self.init_weights()
  File "/home/jinw/VQA/KVQ/models/backbones/swin_backbone.py", line 1038, in init_weights
    self.load_swin(self.pretrained, strict=False)  # , logger=logger)
  File "/home/jinw/VQA/KVQ/models/backbones/swin_backbone.py", line 938, in load_swin
    state_dict = torch.load(load_path)["state_dict"]
  File "/home/jinw/anaconda3/envs/KVQ/lib/python3.8/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/jinw/anaconda3/envs/KVQ/lib/python3.8/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/jinw/anaconda3/envs/KVQ/lib/python3.8/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained_weights/swin_tiny_patch244_window877_kinetics400_1k.pth'

**Comment by zhuzhu18** [comment]
这里可以下载：
https://github.com/SwinTransformer/storage/releases/download/v1.0.4/swin_tiny_patch244_window877_kinetics400_1k.pth
